# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
    minecraft_version=26.1.2
    loader_version=0.19.2
    loom_version=1.16-SNAPSHOT

# Mod Properties
	mod_version = 0.11.0
	maven_group = dev.smithed
	archives_base_name = radon

# Dependencies
    fabric_api_version=0.148.0+26.1.2
	lithium_version=mc26.1.2-0.24.2
